project_id = "yuhbvzjniylkruaylxzz"

[functions.create-payment-intent]
verify_jwt = false

[functions.capture-payment]
verify_jwt = false

[functions.process-stripe-payment]
verify_jwt = false

[functions.get-payment-intent]
verify_jwt = false

[functions.send-admin-email]
verify_jwt = true

[functions.send-admin-sms]
verify_jwt = true

[functions.verify-id-document]
verify_jwt = true

[functions.auth-email-hook]
verify_jwt = false

[functions.send-signature-email]
verify_jwt = false