project_id = "yuhbvzjniylkruaylxzz"

[functions.mark-transaction-paid]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.capture-payment]
verify_jwt = false

[functions.process-stripe-payment]
verify_jwt = false

[functions.get-payment-intent]
verify_jwt = false

[functions.send-admin-email]
verify_jwt = true

[functions.send-admin-sms]
verify_jwt = true

[functions.verify-id-document]
verify_jwt = true

[functions.auth-email-hook]
verify_jwt = false

[functions.send-signature-email]
verify_jwt = false

[functions.get-stripe-publishable-key]
verify_jwt = false

[functions.cinetpay-payout]
verify_jwt = true

[functions.cinetpay-webhook]
verify_jwt = false

[functions.cinetpay-payment]
verify_jwt = false

[functions.cinetpay-payment-webhook]
verify_jwt = false

[functions.get-cinetpay-config]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.cancel-reservation]
verify_jwt = false